config/routes.rb
References::Application.routes.draw do

   root 'home#index'

   get '/download', to: 'download#index'
   post '/download', to: 'download#index'

   get '/upload', to: 'upload#index'
   post '/upload', to: 'upload#index'

   get '/update', to: 'update#index'
   post '/update', to: 'update#index'

   get '/information', to: 'information#index'
   post '/information', to: 'information#index'

   resources :download do
     post :download, on: :collection
   end

   resources :home do
     post :downloadErrorFile, on: :collection
   end

   resources :information do
     post :downloadInformationFile, on: :collection
   end

   resources :update do
     post :addPerson, on: :collection
     post :deletePerson, on: :collection
     post :addReference, on: :collection
     post :deleteReference, on: :collection
     post :changeReference, on: :collection
   end

    post :action=>'onUpload', :controller=>'upload'

  

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index

  end

  def downloadErrorFile
      send_file Rails.root.join('public', 'uploads', 'Errors.txt'), :type => 'application/text'
  end
end

app/views/home/index.erb
<h1>Welcome to References</h1>
<h2>"Where you know who you know"</h2>


<h2><label>Select an option</label> : </h2>
<%= button_to('Upload Input File', upload_path()) %>
<br/>
<%= button_to('Download Input File', download_path()) %>
<br/>
<%= button_to('Update References', update_path()) %>
<br/>
<%= button_to('View Information', information_path()) %>
<br/>
<%= form_tag(controller: :home, action: :downloadErrorFile,
             :multipart => true) do %>
    <%= submit_tag "Download Error File" %>
<% end %>